### ISSUE TITLE
Delay and debounce API calls for security?

### ISSUE THREAD

**Issue by dnotes** [detroitenglish/pw-pwnage-cfworker#2]
I notice that in the demo you are checking the API with every keystroke above 5 characters. I think the API should only be called after the minimum number of characters is reached, and only after the typing is finished (so debounce to .3s or so).

I'd suggest 8 for the minimum number of characters to check, as that's the absolute low end of password length among all the security standards and recommendations I've ever read. It seems that there just isn't any such thing as a secure 6-character password.

As for the debounce: AFAIK k-anon protects against disclosing passwords by transmitting only a portion of the hash; but if you transmit that portion on each keystroke, wouldn't that be pretty easy for a bad actor (e.g. MITM, Evil Troy Hunt, etc.) to reconstruct? Even starting with five characters, that's still only tens of billions of possibilities for the most common characters, which means it would be possible for an attacker to start out with a sha1 hashes for all common combos of 5 characters, and then add a character and compare each subsequent hash. I'm not sure about this, but that is why I'm thinking that debouncing is desirable / necessary.

**Comment by detroitenglish** [comment]
Thanks for your concern.

If an attacker MITM's my app and Cloudflare, it's already game over and therefore no cause for concern. Same goes for an Evil Cloudflare - every byte of my application data goes through their network, so game-over.

A month ago, [Troy Hunt revealed his API was getting 54+ million requests per week](https://twitter.com/troyhunt/status/1011871593830551552) (appx. 89 per second). Every one of those requests goes through one of Cloudflare's 151 data centers, leaving no way for Evil Troy to correlate requests to specific users behind CF's proxy.

On top of that, only 8% of those requests are even visible to Evil Troy - the remaining [92% are cached responses from the Cloudflare edge](https://twitter.com/troyhunt/status/1011871596603060225). Evil Troy would need to gain control of Cloudflare itself for hash inference to be a viable attack vector, but it's already game-over so why bother?  Considering this scenario [breaks the core principles of engineering](http://www.gelato.unsw.edu.au/archives/git/0504/0885.html).

Anyways I'm closing this issue as outside the scope of this CF-Worker script. Request governing isn't possible in a CF-Worker and would need to be implemented client side.
